#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.why.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
bubble:
  database: mysql
---
server:
  port: 8002
spring:
  profiles:
    active: prod # 激活开发环境配置
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.10.11:3306/springcloud_db02?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka-svc1.com:6001/eureka,http://eureka-svc.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址
feign:
  hystrix:
    enabled: true # 开启服务熔断器
---
server:
  port: 8001
spring:
  profiles:
    active: dev # 激活开发环境配置
  application:
    name: microservice-product-config #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.10.11:3306/springcloud_db02?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: false # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka-svc1.com:6001/eureka,http://eureka-svc.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址

feign:
  hystrix:
    enabled: true # 开启服务熔断器
